  
spring: 
    jpa:
        database: POSTGRESQL
        hibernate.ddl-auto: update
    database:
        driverClassName: org.postgresql.Driver

    datasource:
        url: jdbc:postgresql://35.222.221.100:5432/loja
        username: postgres
        password: everton
